version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pub-thursday-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c04yqf8kr2eq"
s3_prefix = "pub-thursday-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
